#! /bin/bash

#Author: Yogesh k
#Created date:
#Modified date:

#Description:
#Usage:

echo Hello, ${USER^}
echo I will now back up your home directory, $HOME
currentdir=$(pwd)
#echo $currentdir
echo You are running this script from $currentdir.
echo Therefore, I will save the backup in $currentdir
tar -cf $currentdir/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar $HOME 2>/dev/null
exit 0
